version: '3.8'
services:
    redis:
        image: 'redis:alpine'
        container_name: redis_server
        ports:
            - '6379:6379' # Expose Redis port
        volumes:
            - redis-data:/data
        restart: always

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node_app
        ports:
            - '3000:3000'
        environment:
            - HOST=0.0.0.0
            - PORT=3000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - .:/usr/src/app
        depends_on:
            - redis
        restart: always

volumes:
    redis-data:
